question 1: Create a 3x3x3 array with random values

In [4]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.49190547 0.75495743 0.73016752]
  [0.37280604 0.51522454 0.63154681]
  [0.59141808 0.15226975 0.91072544]]

 [[0.16363488 0.88067499 0.81048232]
  [0.84892322 0.23586036 0.24445938]
  [0.52487983 0.40341407 0.02528025]]

 [[0.90553034 0.20527428 0.55142774]
  [0.3755185  0.78645788 0.39310281]
  [0.95845354 0.80887757 0.68515443]]]


question 2:Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [32]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
arr.shape
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [35]:
brr=arr[:,:]
brr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [39]:
brr[1][0]=1
brr[2][1]=2
brr[3][2]=3
brr[4][3]=4

brr

array([[ 1,  1,  3,  4,  5],
       [ 1,  7,  8,  9, 10],
       [11,  2, 13, 14, 15],
       [16, 17,  3, 19, 20],
       [21, 22, 23,  4, 25]])

question 3:Create a 8x8 matrix and fill it with a checkerboard pattern

In [40]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


question 4:Normalize a 5x5 random matrix

In [41]:
import numpy as np

print("Original Array:",)
print(arr)
arrmax=arr.max()
arrmin=arr.min()
arr = (arr - arrmin)/(arrmax - arrmin)
print("After normalization:")
print(arr)

Original Array:
[[ 1  1  3  4  5]
 [ 1  7  8  9 10]
 [11  2 13 14 15]
 [16 17  3 19 20]
 [21 22 23  4 25]]
After normalization:
[[0.         0.         0.08333333 0.125      0.16666667]
 [0.         0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.04166667 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.08333333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.125      1.        ]]


question 5: How to find common values between two arrays?

In [42]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


question 6:How to get the dates of yesterday, today and tomorrow?

In [43]:
import datetime 
today = datetime.date.today()
yesterday = today - datetime.timedelta(days = 1)
tomorrow = today + datetime.timedelta(days = 1) 
print('Yesterday : ',yesterday)
print('Today : ',today)
print('Tomorrow : ',tomorrow)

Yesterday :  2020-07-25
Today :  2020-07-26
Tomorrow :  2020-07-27


question 7:Consider two random array A and B, check if they are equal

In [45]:
import numpy as np
print("First array:")
print(arr)
print("Second array:")
print(brr)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(arr,brr)
print(array_equal)

First array:
[[0.         0.         0.08333333 0.125      0.16666667]
 [0.         0.25       0.29166667 0.33333333 0.375     ]
 [0.41666667 0.04166667 0.5        0.54166667 0.58333333]
 [0.625      0.66666667 0.08333333 0.75       0.79166667]
 [0.83333333 0.875      0.91666667 0.125      1.        ]]
Second array:
[[ 1  1  3  4  5]
 [ 1  7  8  9 10]
 [11  2 13 14 15]
 [16 17  3 19 20]
 [21 22 23  4 25]]
Test above two arrays are equal or not!
False


question 8:Create random vector of size 10 and replace the maximum value by 0

In [46]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by -1:")
print(x)

Original array:
[0.81566216 0.24440401 0.60501896 0.13111476 0.61652247 0.06943701
 0.1901883  0.90842996 0.32618146 0.0808309 ]
Maximum value replaced by -1:
[0.81566216 0.24440401 0.60501896 0.13111476 0.61652247 0.06943701
 0.1901883  0.         0.32618146 0.0808309 ]


question 9:How to print all the values of an array?

In [62]:
import numpy as np
import sys
np.set_printoptions(threshold=sys.maxsize)
x = np.ones((4, 4))
print(x)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [64]:
import numpy as np
print("Original matrix:\n")

print(brr)
print("\nSubtract the mean of each row of the said matrix:\n")
crr = brr - brr.mean(axis=1, keepdims=True)
print(crr)

Original matrix:

[[ 1  1  3  4  5]
 [ 1  7  8  9 10]
 [11  2 13 14 15]
 [16 17  3 19 20]
 [21 22 23  4 25]]

Subtract the mean of each row of the said matrix:

[[ -1.8  -1.8   0.2   1.2   2.2]
 [ -6.    0.    1.    2.    3. ]
 [  0.   -9.    2.    3.    4. ]
 [  1.    2.  -12.    4.    5. ]
 [  2.    3.    4.  -15.    6. ]]


question 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [2]:
import numpy as np
import pandas  as pd
a = np.ones(10)
b = np.random.randint(0,len(a),20)
a += np.bincount(b, minlength=len(a))
print(a)

[2. 2. 3. 2. 4. 1. 2. 5. 6. 3.]


question 12.How to get the diagonal of a dot product?

In [3]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
ab = np.dot(A, B)
print("Dot product Matrix \n")
print(ab)
print()
print("Diagonal\n")
print(np.diag(ab))

Dot product Matrix 

[[ 75 108 148]
 [ 28  70 100]
 [ 23  56  72]]

Diagonal

[75 70 72]


question 13.How to find the most frequent value in an array?

In [4]:
m= np.random.randint(0,100,100)
print (m)
print('Frequent Number:', np.bincount(m).argmax())

[39 20 29 45 71 76 33 82 12 78 89 36 53 72 89 21 20 98 60 69 55 73 85 85
  9 96 41 16  4  4 88 97 44 91 63 63 78 27 96 48 48 47  3  5 76 24 65 65
 48  5 30 21 34 47 77 79  6 26 17 85 31 74  1 66 78 37 91 17 96 55 27  0
 43 39 40 28 26 12 30 55 53 35 36 85 79 27 98  3 95 54 61 11  6 62 53 80
  9 48 40 14]
Frequent Number: 48


question 14.How to get the n largest values of an array

In [5]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 10
# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9997 9999 9998 9996 9994 9995 9993 9992 9990 9991]


question 15.How to create a record array from a regular array?

In [7]:
a = np.array([("python", 2.5, 3),
              ("hacker", 3.6, 2)])
b = np.core.records.fromarrays(a.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
b

rec.array([(b'python', 2.5, 3), (b'hacker', 3.6, 2)],
          dtype=[('col1', 'S8'), ('col2', '<f8'), ('col3', '<i8')])